# Generated by Django 2.2.15 on 2020-11-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=100)),
                ('grad_year', models.IntegerField(help_text="Form e.g '2022'")),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=300)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('division', models.CharField(help_text='A, N, or U', max_length=30)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(help_text='Type of competition', max_length=500)),
                ('score', models.IntegerField()),
                ('rank_in_room', models.IntegerField()),
                ('debate_round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Round')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Student')),
            ],
        ),
    ]
