# Generated by Django 2.2.15 on 2020-11-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_debate', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='performance',
            name='form',
            field=models.ForeignKey(help_text='Type of competition', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Type'),
        ),
    ]
