# Generated by Django 2.2.15 on 2020-11-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201120_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='comment',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
