# Generated by Django 2.2.15 on 2020-11-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20201120_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
