# Generated by Django 2.2.15 on 2020-11-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_round_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='performances',
        ),
        migrations.AddField(
            model_name='performance',
            name='debate_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Round'),
        ),
    ]
