# Generated by Django 2.2.15 on 2020-11-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20201120_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='debate_round',
        ),
        migrations.RemoveField(
            model_name='round',
            name='form',
        ),
        migrations.AddField(
            model_name='performance',
            name='form',
            field=models.ForeignKey(help_text='Type of competition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Type'),
        ),
        migrations.AddField(
            model_name='round',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Performance'),
        ),
    ]
