# Generated by Django 2.2.15 on 2020-11-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20201121_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='tournament',
        ),
        migrations.AddField(
            model_name='performance',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Tournament'),
        ),
    ]
