# Generated by Django 2.2.15 on 2020-11-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201121_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('holders', models.ManyToManyField(to='database.Student')),
            ],
        ),
    ]
