# Generated by Django 2.2.15 on 2020-11-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Tournament'),
        ),
    ]
