# Generated by Django 2.2.15 on 2020-11-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_award_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='rank_in_room_total',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='score',
        ),
    ]
