# Generated by Django 2.2.15 on 2020-11-22 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20201122_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='form',
        ),
        migrations.AddField(
            model_name='round',
            name='form',
            field=models.ForeignKey(help_text='Type of competition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Type'),
        ),
    ]
