# Generated by Django 2.2.15 on 2020-11-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20201122_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='wins',
        ),
    ]
