# Generated by Django 2.2.15 on 2020-11-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_remove_performance_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='comment',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
