# Generated by Django 2.2.15 on 2020-11-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20201122_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Type'),
        ),
    ]
