# Generated by Django 2.2.15 on 2020-11-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_award_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='name',
            new_name='placement',
        ),
    ]
