# Generated by Django 2.2.15 on 2020-11-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20201122_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
