# Generated by Django 3.0.4 on 2020-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_award_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='performance',
        ),
        migrations.AddField(
            model_name='award',
            name='performance',
            field=models.ManyToManyField(to='database.Performance'),
        ),
    ]
